### ISSUE TITLE
Notification to show at top of viewport

### ISSUE THREAD

**Issue by AusDude** [vincentkeizer/notify#3]
Hi there,
Really loving the simplicity of Notify.
I am however having an issue in showing the Notification in a Div Container that scrolls with the top of the  viewport. 
Does the .Notify CSS override any container CSS at all?
Many thanks.

**Comment by vincentkeizer** [comment]
Hi AusDude,

Thank you.
It does override the 'position' css of the container element (the appendTo setting, which defaults to 'body'). 
When the position is 'static' it will be changed to 'relative'.
Regards,

Vincent
